Update ghaction-import
Used crazy-max/ghaction-import-gpg@v5.0.0 instead of hashicorp/ghaction-import-gpg@v2.1.0 as a
workaround for the github action failure:
gpg-agent[1778]: directory '/home/runner/.gnupg' created
gpg-agent[1778]: directory '/home/runner/.gnupg/private-keys-v1.d' created
gpg-agent: a gpg-agent is already running - not starting a new one
Error: Process completed with exit code 2.

See: https://github.com/hashicorp/ghaction-import-gpg/issues/11#issuecomment-1185107410